name: Build Driver with Official Container

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-2019 # Required for this specific container

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build using WDK container
      uses: microsoft/windows-driver-samples-action@v1
      with:
        build-command: 'build -cZ'
        # The container automatically finds and builds the driver.

    - name: Upload driver artifact
      uses: actions/upload-artifact@v4
      with:
        name: Driver-artifact
        # The path inside the container is complex, let's find the file
        path: '**/*.sys'
        if-no-files-found: error
