name: Build MyDriver

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Download and install WDK
      run: |
        Invoke-WebRequest -Uri 'https://go.microsoft.com/fwlink/?linkid=2128854' -OutFile 'wdksetup.exe'
        Start-Process -FilePath 'wdksetup.exe' -ArgumentList '/q' -Wait
      shell: pwsh

    - name: Build driver
      run: |
        cd MyDriver
        call "C:\Program Files (x86 )\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        msbuild MyDriver.vcxproj /t:build /p:Configuration=Release /p:Platform=x64
      shell: cmd

    - name: Upload driver artifact
      uses: actions/upload-artifact@v4
      with:
        name: MyDriver.sys
        path: MyDriver/x64/Release/MyDriver.sys
