name: Build WDM Driver

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install WDK
      run: |
        Invoke-WebRequest -Uri 'https://go.microsoft.com/fwlink/?linkid=2128854' -OutFile 'wdksetup.exe'
        Start-Process -FilePath 'wdksetup.exe' -ArgumentList '/q' -Wait
      shell: pwsh

    - name: Build Driver
      run: |
        "C:\Program Files (x86 )\Windows Kits\10\build\build.exe" -cZ
      shell: cmd

    - name: Upload Driver Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Driver-artifact
        path: objfre_win7_amd64/amd64/Driver.sys
