name: Manual Driver Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Visual Studio Build Tools
      uses: microsoft/setup-msbuild@v2

    - name: Install WDK
      run: |
        Invoke-WebRequest -Uri 'https://go.microsoft.com/fwlink/?linkid=2128854' -OutFile 'wdksetup.exe'
        Start-Process -FilePath 'wdksetup.exe' -ArgumentList '/q' -Wait
      shell: pwsh

    - name: Build the Driver
      run: |
        call "C:\Program Files (x86 )\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
        call "C:\Program Files (x86)\Windows Kits\10\bin\setenv.bat" "C:\Program Files (x86)\Windows Kits\10" x64
        build -cZ
      shell: cmd

    - name: Find and Upload Artifact
      id: find_artifact
      run: |
        $sysFile = Get-ChildItem -Path . -Recurse -Filter Driver.sys | Select-Object -First 1
        if ($null -eq $sysFile) {
          Write-Error "Driver.sys not found after build!"
          exit 1
        }
        echo "Found driver at: $($sysFile.FullName)"
        echo "artifact_path=$($sysFile.FullName)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      shell: pwsh

    - name: Upload Driver
      uses: actions/upload-artifact@v4
      with:
        name: Built-Driver
        path: ${{ env.artifact_path }}
